# Generated by Django 5.2.4 on 2025-08-04 13:12

import wallet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_number',
            field=models.CharField(blank=True, default=wallet.models.generate_account_number, max_length=10, null=True, unique=True),
        ),
    ]
