# Generated by Django 5.2.4 on 2025-08-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_wallet_wallet_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reference',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
